question_data = [{"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, "
                              "is Zelda.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "easy",
                  "question": "Clefairy was intended to be Ash&#039;s starting Pok&eacute;mon in the pilot episode of the cartoon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 RPG "
                              "&quot;Undertale&quot;.",
                  'correct_answer': "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for "
                              "US$1.65 billion in stock.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Greenland is covered with grass and Iceland covered with ice.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "The Republic of Malta is the smallest microstate worldwide.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Gumbo is a stew that originated in Louisiana.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Linus Torvalds created Linux and Git.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "easy",
                  "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about "
                              "MySpace founder Tom Anderson.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The programming language &quot;Python&quot; is based off a modified version of "
                              "&quot;JavaScript&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Books", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The &quot;Berenstein Bears&quot; is the correct spelling of the educational "
                              "children&#039;s book series&#039; name.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "It is automatically considered entrapment in the United States if the police sell you "
                              "illegal substances without revealing themselves.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The &#039;Squaring the Circle&#039; problem is solvable.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "&quot;Half-Life 2&quot; runs on the Source Engine.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of "
                              "urine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Gadgets", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The communication protocol NFC stands for Near-Field Control.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Ottawa is the capital of Canada.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In &quot;Super Mario 3D World&quot;, the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Minecraft can be played with a virtual reality headset.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness Vest&quot;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Books", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Stephen Chbosky wrote the book &#039;The Perks of Being A Wallflower&#039;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Board Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "There is a Donald Trump Board Game, which was made in 1989.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Comics", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The Windows 7 operating system has six main editions.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "easy", "question": "Daft Punk originated in France.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Kublai Khan is the grandchild of Genghis Khan?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "easy",
                  "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Psychology is the science of behavior and mind.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy",
                  "question": "A plant that has a life cycle for more than a year is known as an annual.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "The internet browser Firefox is named after the Red Panda.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Doki Doki Literature Club was developed in Japan.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Books", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
